### ISSUE TITLE
Why create dapp failed?

### ISSUE THREAD

**Issue by luxcgo** [movefuns/SuiStartrek#59]
```sh
$ pnpm create @mysten/create-dapp

.../Library/pnpm/store/v3/tmp/dlx-6404   | +108 +++++++++++
.../Library/pnpm/store/v3/tmp/dlx-6404   | Progress: resolved 108, reused 108, downloaded 0, added 108, done
/Users/lucas/Library/pnpm/store/v3/tmp/dlx-6404/node_modules/.pnpm/registry.npmmirror.com+@mysten+create-dapp@0.1.3_@tanstack+react-query@5.8.4_react-dom@18.2.0_react@18.2.0/node_modules/@mysten/create-dapp/dist/index.js:12
const { values: args } = (0, util_1.parseArgs)({
                                              ^

TypeError: (0 , util_1.parseArgs) is not a function
    at Object.<anonymous> (/Users/lucas/Library/pnpm/store/v3/tmp/dlx-6404/node_modules/.pnpm/registry.npmmirror.com+@mysten+create-dapp@0.1.3_@tanstack+react-query@5.8.4_react-dom@18.2.0_react@18.2.0/node_modules/@mysten/create-dapp/dist/index.js:12:47)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/lucas/Library/pnpm/store/v3/tmp/dlx-6404/node_modules/.pnpm/registry.npmmirror.com+@mysten+create-dapp@0.1.3_@tanstack+react-query@5.8.4_react-dom@18.2.0_react@18.2.0/node_modules/@mysten/create-dapp/bin/index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

```
$ pnpm -v                                                                                                                                                         1 ✘
8.10.5
```

mac arm64

**Comment by 2niuhe** [comment]
check your nodejs version

`node -v`

The dapp dependency is 

```
  "dependencies": {
    "@types/node": "^20.4.2",
    "enquirer": "^2.4.1",
    "@mysten/dapp-kit": "0.9.0",
    "@mysten/sui.js": "0.46.1"
  },
```

my env is

```shell
(base) pnpm --version
8.10.5
(base)  npm -v
10.2.3
(base)  node -v
v21.2.0
```

**Comment by 2niuhe** [comment]
problem solved. @uvd

**Comment by uvd** [comment]
@2niuhe    https://suiexplorer.com/txblock/2dvpSc1uJxqdKoKJoruy4KfmqbiVhDJouooQB4NxUezc
